### ISSUE TITLE
Doesn't work with manual installation

### ISSUE THREAD

**Issue by alex3kov** [manicmaniac/coconut.vim#2]
Vim 8.1 here.  
I put extracted directory to `~/.vim/`:
```
ll ~/.vim/coconut.vim-master/
total 16K
drwxr-xr-x 2 username users 4.0K Oct 25 15:39 ftdetect
drwxr-xr-x 2 username users 4.0K Oct 10  2017 indent
-rw-r--r-- 1 username users  388 Oct 10  2017 README.md
drwxr-xr-x 2 username users 4.0K Oct 10  2017 syntax
```
And added this to `~/.vimrc`:
```
" Coconut syntax
source ~/.vim/coconut.vim-master/indent/coconut.vim
source ~/.vim/coconut.vim-master/syntax/coconut.vim
source ~/.vim/coconut.vim-master/ftdetect/coconut.vim
```
But it doesn't highlight syntax when opening `.coco` files. However, if after opening a `.coco` file I do manual `:source ~/.vim/coconut.vim-master/syntax/coconut.vim` - the syntax is highlighted.

**Comment by ghost** [comment]
@alex3kov I think your .vimrc may cause the problem.

How does it work when you change .vimrc like the following?

```
" Coconut syntax
set runtimepath+=~/.vim/coconut.vim-master
syntax on
```

**Comment by alex3kov** [comment]
@ymizushima Actually I've read about Vim 8 native packages (https://shapeshed.com/vim-packages/) and placed this into a different directory:
```
~: ll .vim/pack/my-plugins/start/coconut.vim/*
-rw------- 1 username users 388 Oct 27 15:38 .vim/pack/my-plugins/start/coconut.vim/README.md

.vim/pack/my-plugins/start/coconut.vim/ftdetect:
total 512
-rw------- 1 username users 324 Oct 27 15:38 coconut.vim

.vim/pack/my-plugins/start/coconut.vim/indent:
total 8.0K
-rw------- 1 username users 5.7K Oct 27 15:38 coconut.vim

.vim/pack/my-plugins/start/coconut.vim/syntax:
total 16K
-rw------- 1 username users 14K Oct 27 15:38 coconut.vim
```
And it started working (no additions to `vimrc` needed). Maybe your manual installation instructions need to be updated?

**Comment by manicmaniac** [comment]
@alex3kov You're right, there are several ways to install third party plugins.
Before Vim 8 (and even in Vim 8), you can install this plugin by copying each directories into ~/.vim/.
If you prefer installing plugins into subdirectories, you have to add all subdirectories to `runtimepath` 
 (`source`ing plugins in .vimrc might not work).

So I think the current install instruction is still correct although adding new install instruction will make it better.
Thank you for reporting an issue!
